# generated by datamodel-codegen:
#   filename:  convai-analytics-api.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class BreakdownRow(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    group: Annotated[str, Field(title="Group")]
    sample_count: Annotated[
        int | None, Field(alias="sampleCount", title="Samplecount")
    ] = 0
    value: Annotated[float | None, Field(title="Value")] = None


class ComponentSpan(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    attributes: Annotated[dict[str, Any] | None, Field(title="Attributes")] = None
    duration_ms: Annotated[
        float | None, Field(alias="durationMs", title="Durationms")
    ] = 0.0
    end_time: Annotated[
        AwareDatetime | None, Field(alias="endTime", title="Endtime")
    ] = None
    error_code: Annotated[str | None, Field(alias="errorCode", title="Errorcode")] = (
        None
    )
    metric_name: Annotated[
        str | None, Field(alias="metricName", title="Metricname")
    ] = None
    metric_type: Annotated[
        str | None, Field(alias="metricType", title="Metrictype")
    ] = None
    model: Annotated[str | None, Field(title="Model")] = None
    processor: Annotated[str | None, Field(title="Processor")] = None
    provider: Annotated[str | None, Field(title="Provider")] = None
    start_time: Annotated[AwareDatetime, Field(alias="startTime", title="Starttime")]
    status: Annotated[str | None, Field(title="Status")] = None


class Operator(Enum):
    equals = "equals"
    not_equals = "notEquals"
    contains = "contains"
    not_contains = "notContains"
    gt = "gt"
    gte = "gte"
    lt = "lt"
    lte = "lte"
    set = "set"
    not_set = "notSet"
    in_date_range = "inDateRange"
    not_in_date_range = "notInDateRange"


class CubeFilter(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    member: Annotated[str, Field(title="Member")]
    operator: Annotated[Operator, Field(title="Operator")]
    values: Annotated[list[str] | None, Field(title="Values")] = None


class Order(Enum):
    asc = "asc"
    desc = "desc"


class CubeTimeDimension(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    date_range: Annotated[
        str | list[str] | None, Field(alias="dateRange", title="Daterange")
    ] = None
    dimension: Annotated[str, Field(title="Dimension")]
    granularity: Annotated[str | None, Field(title="Granularity")] = None


class EffectiveRange(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    end_time: Annotated[AwareDatetime, Field(alias="endTime", title="Endtime")]
    start_time: Annotated[AwareDatetime, Field(alias="startTime", title="Starttime")]


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    environment: Annotated[str, Field(title="Environment")]
    status: Annotated[str, Field(title="Status")]
    version: Annotated[str, Field(title="Version")]


class Visibility(Enum):
    public = "public"
    enterprise = "enterprise"
    internal = "internal"


class MetricDefinition(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Annotated[str, Field(title="Description")]
    metric_name: Annotated[str, Field(alias="metricName", title="Metricname")]
    metric_type: Annotated[str, Field(alias="metricType", title="Metrictype")]
    supports_percentiles: Annotated[
        bool | None, Field(alias="supportsPercentiles", title="Supportspercentiles")
    ] = False
    unit: Annotated[str | None, Field(title="Unit")] = None
    visibility: Annotated[Visibility, Field(title="Visibility")]


class RegressionRow(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    baseline_value: Annotated[
        float, Field(alias="baselineValue", title="Baselinevalue")
    ]
    current_value: Annotated[float, Field(alias="currentValue", title="Currentvalue")]
    group: Annotated[str, Field(title="Group")]
    relative_change: Annotated[
        float, Field(alias="relativeChange", title="Relativechange")
    ]
    sample_count: Annotated[
        int | None, Field(alias="sampleCount", title="Samplecount")
    ] = 0
    significant: Annotated[bool, Field(title="Significant")]


class Backend(Enum):
    cube = "cube"
    bq = "bq"


class ResponseMeta(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    backend: Annotated[Backend, Field(title="Backend")]
    cache_hit: Annotated[bool | None, Field(alias="cacheHit", title="Cachehit")] = False
    effective_range: Annotated[EffectiveRange, Field(alias="effectiveRange")]
    freshness_at: Annotated[
        AwareDatetime, Field(alias="freshnessAt", title="Freshnessat")
    ]
    sample_count: Annotated[int, Field(alias="sampleCount", title="Samplecount")]


class SessionSummary(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    app_key: Annotated[str | None, Field(alias="appKey", title="Appkey")] = None
    character_id: Annotated[
        str | None, Field(alias="characterId", title="Characterid")
    ] = None
    duration_sec: Annotated[
        float | None, Field(alias="durationSec", title="Durationsec")
    ] = 0.0
    end_time: Annotated[
        AwareDatetime | None, Field(alias="endTime", title="Endtime")
    ] = None
    error_count: Annotated[
        int | None, Field(alias="errorCount", title="Errorcount")
    ] = 0
    experience_id: Annotated[
        str | None, Field(alias="experienceId", title="Experienceid")
    ] = None
    interaction_count: Annotated[
        int | None, Field(alias="interactionCount", title="Interactioncount")
    ] = 0
    p95_end_to_end_ms: Annotated[
        float | None, Field(alias="p95EndToEndMs", title="P95Endtoendms")
    ] = 0.0
    session_id: Annotated[str, Field(alias="sessionId", title="Sessionid")]
    start_time: Annotated[
        AwareDatetime | None, Field(alias="startTime", title="Starttime")
    ] = None


class SessionTimelineEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    attributes: Annotated[dict[str, Any] | None, Field(title="Attributes")] = None
    event_time: Annotated[AwareDatetime, Field(alias="eventTime", title="Eventtime")]
    interaction_id: Annotated[
        str | None, Field(alias="interactionId", title="Interactionid")
    ] = None
    metric_name: Annotated[str, Field(alias="metricName", title="Metricname")]
    metric_type: Annotated[
        str | None, Field(alias="metricType", title="Metrictype")
    ] = None
    processor: Annotated[str | None, Field(title="Processor")] = None
    status: Annotated[str | None, Field(title="Status")] = None
    value: Annotated[float | None, Field(title="Value")] = None


class SummaryResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    error_count: Annotated[int, Field(alias="errorCount", title="Errorcount")]
    interactions: Annotated[int, Field(title="Interactions")]
    meta: ResponseMeta
    p50_end_to_end_ms: Annotated[
        float, Field(alias="p50EndToEndMs", title="P50Endtoendms")
    ]
    p95_end_to_end_ms: Annotated[
        float, Field(alias="p95EndToEndMs", title="P95Endtoendms")
    ]
    p99_end_to_end_ms: Annotated[
        float, Field(alias="p99EndToEndMs", title="P99Endtoendms")
    ]
    sessions: Annotated[int, Field(title="Sessions")]
    unique_end_users: Annotated[
        int, Field(alias="uniqueEndUsers", title="Uniqueendusers")
    ]


class TimeseriesPoint(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    bucket_start: Annotated[
        AwareDatetime, Field(alias="bucketStart", title="Bucketstart")
    ]
    group: Annotated[str | None, Field(title="Group")] = None
    value: Annotated[float | None, Field(title="Value")] = None


class Granularity(Enum):
    minute = "minute"
    hour = "hour"
    day = "day"


class TimeseriesResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    granularity: Annotated[Granularity, Field(title="Granularity")]
    measure: Annotated[str, Field(title="Measure")]
    meta: ResponseMeta
    points: Annotated[list[TimeseriesPoint], Field(title="Points")]


class ValidationError(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ctx: Annotated[dict[str, Any] | None, Field(title="Context")] = None
    input: Annotated[Any | None, Field(title="Input")] = None
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class BreakdownResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    group_by: Annotated[str, Field(alias="groupBy", title="Groupby")]
    measure: Annotated[str, Field(title="Measure")]
    meta: ResponseMeta
    rows: Annotated[list[BreakdownRow], Field(title="Rows")]


class CatalogResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    meta: ResponseMeta
    metrics: Annotated[list[MetricDefinition], Field(title="Metrics")]


class CubeQueryRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    dimensions: Annotated[list[str] | None, Field(title="Dimensions")] = None
    filters: Annotated[list[CubeFilter] | None, Field(title="Filters")] = None
    limit: Annotated[int | None, Field(ge=1, le=5000, title="Limit")] = 1000
    measures: Annotated[list[str] | None, Field(title="Measures")] = None
    order: Annotated[dict[str, Order] | None, Field(title="Order")] = None
    segments: Annotated[list[str] | None, Field(title="Segments")] = None
    time_dimensions: Annotated[
        list[CubeTimeDimension] | None,
        Field(alias="timeDimensions", title="Timedimensions"),
    ] = None


class CubeQueryResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Annotated[list[dict[str, Any]], Field(title="Data")]
    meta: ResponseMeta


class HTTPValidationError(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class InteractionTrace(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    app_key: Annotated[str | None, Field(alias="appKey", title="Appkey")] = None
    character_id: Annotated[
        str | None, Field(alias="characterId", title="Characterid")
    ] = None
    end_time: Annotated[
        AwareDatetime | None, Field(alias="endTime", title="Endtime")
    ] = None
    end_user_id: Annotated[str | None, Field(alias="endUserId", title="Enduserid")] = (
        None
    )
    failure_stage: Annotated[
        str | None, Field(alias="failureStage", title="Failurestage")
    ] = None
    interaction_id: Annotated[str, Field(alias="interactionId", title="Interactionid")]
    interaction_type: Annotated[
        str | None, Field(alias="interactionType", title="Interactiontype")
    ] = None
    meta: ResponseMeta
    session_id: Annotated[str | None, Field(alias="sessionId", title="Sessionid")] = (
        None
    )
    spans: Annotated[list[ComponentSpan], Field(title="Spans")]
    start_time: Annotated[
        AwareDatetime | None, Field(alias="startTime", title="Starttime")
    ] = None
    terminal_status: Annotated[
        str | None, Field(alias="terminalStatus", title="Terminalstatus")
    ] = None
    total_duration_ms: Annotated[
        float | None, Field(alias="totalDurationMs", title="Totaldurationms")
    ] = 0.0


class RegressionResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    meta: ResponseMeta
    rows: Annotated[list[RegressionRow], Field(title="Rows")]


class SessionDetail(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    app_key: Annotated[str | None, Field(alias="appKey", title="Appkey")] = None
    character_id: Annotated[
        str | None, Field(alias="characterId", title="Characterid")
    ] = None
    end_time: Annotated[
        AwareDatetime | None, Field(alias="endTime", title="Endtime")
    ] = None
    events: Annotated[list[SessionTimelineEvent], Field(title="Events")]
    experience_id: Annotated[
        str | None, Field(alias="experienceId", title="Experienceid")
    ] = None
    meta: ResponseMeta
    session_id: Annotated[str, Field(alias="sessionId", title="Sessionid")]
    start_time: Annotated[
        AwareDatetime | None, Field(alias="startTime", title="Starttime")
    ] = None


class SessionListResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    meta: ResponseMeta
    next_cursor: Annotated[
        str | None, Field(alias="nextCursor", title="Nextcursor")
    ] = None
    sessions: Annotated[list[SessionSummary], Field(title="Sessions")]
