/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe — 200 as long as the process is serving.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe.
         *
         *     Returns 200 when the service is ready to accept traffic. For the initial
         *     shell this is identical to ``/healthz``; future work should check Redis,
         *     Cube, and BigQuery connectivity here and return 503 on backend failure.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Group-by aggregation for a measure (e.g. p95 by provider, count by character) */
        get: operations["breakdown_v1_analytics_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/interactions/{interaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-interaction (trace) waterfall — component spans + provider/model attribution */
        get: operations["interaction_trace_v1_analytics_interactions__interaction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/metrics/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists metric_names the caller's plan can query, with units and descriptions */
        get: operations["metrics_catalog_v1_analytics_metrics_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restricted Cube passthrough — advanced queries within a fixed schema */
        post: operations["cube_query_v1_analytics_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/regression-detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rolling-window p95 regression detection (BigQuery escape hatch) */
        get: operations["regression_detection_v1_analytics_regression_detection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated session list with per-session headline latency + counts */
        get: operations["list_sessions_v1_analytics_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full per-session timeline — one row per metric, ordered by event time */
        get: operations["session_detail_v1_analytics_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top-level KPIs (sessions, end users, interactions, p50/p95/p99 e2e latency, errors) */
        get: operations["summary_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time series for a measure across a time window, bucketed by granularity */
        get: operations["timeseries_v1_analytics_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BreakdownResponse */
        BreakdownResponse: {
            /** Groupby */
            groupBy: string;
            /** Measure */
            measure: string;
            meta: components["schemas"]["ResponseMeta"];
            /** Rows */
            rows: components["schemas"]["BreakdownRow"][];
        };
        /** BreakdownRow */
        BreakdownRow: {
            /** Group */
            group: string;
            /**
             * Samplecount
             * @default 0
             */
            sampleCount: number;
            /** Value */
            value?: number | null;
        };
        /** CatalogResponse */
        CatalogResponse: {
            meta: components["schemas"]["ResponseMeta"];
            /** Metrics */
            metrics: components["schemas"]["MetricDefinition"][];
        };
        /** ComponentSpan */
        ComponentSpan: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            } | null;
            /**
             * Durationms
             * @default 0
             */
            durationMs: number;
            /** Endtime */
            endTime?: string | null;
            /** Errorcode */
            errorCode?: string | null;
            /** Metricname */
            metricName?: string | null;
            /** Metrictype */
            metricType?: string | null;
            /** Model */
            model?: string | null;
            /** Processor */
            processor?: string | null;
            /** Provider */
            provider?: string | null;
            /**
             * Starttime
             * Format: date-time
             */
            startTime: string;
            /** Status */
            status?: string | null;
        };
        /** CubeFilter */
        CubeFilter: {
            /** Member */
            member: string;
            /**
             * Operator
             * @enum {string}
             */
            operator: "equals" | "notEquals" | "contains" | "notContains" | "gt" | "gte" | "lt" | "lte" | "set" | "notSet" | "inDateRange" | "notInDateRange";
            /** Values */
            values?: string[];
        };
        /** CubeQueryRequest */
        CubeQueryRequest: {
            /** Dimensions */
            dimensions?: string[];
            /** Filters */
            filters?: components["schemas"]["CubeFilter"][];
            /**
             * Limit
             * @default 1000
             */
            limit: number;
            /** Measures */
            measures?: string[];
            /** Order */
            order?: {
                [key: string]: "asc" | "desc";
            } | null;
            /** Segments */
            segments?: string[];
            /** Timedimensions */
            timeDimensions?: components["schemas"]["CubeTimeDimension"][];
        };
        /** CubeQueryResponse */
        CubeQueryResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** CubeTimeDimension */
        CubeTimeDimension: {
            /** Daterange */
            dateRange?: string | string[] | null;
            /** Dimension */
            dimension: string;
            /** Granularity */
            granularity?: string | null;
        };
        /** EffectiveRange */
        EffectiveRange: {
            /**
             * Endtime
             * Format: date-time
             */
            endTime: string;
            /**
             * Starttime
             * Format: date-time
             */
            startTime: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Environment */
            environment: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** InteractionTrace */
        InteractionTrace: {
            /** Appkey */
            appKey?: string | null;
            /** Characterid */
            characterId?: string | null;
            /** Endtime */
            endTime?: string | null;
            /** Enduserid */
            endUserId?: string | null;
            /** Failurestage */
            failureStage?: string | null;
            /** Interactionid */
            interactionId: string;
            /** Interactiontype */
            interactionType?: string | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Sessionid */
            sessionId?: string | null;
            /** Spans */
            spans: components["schemas"]["ComponentSpan"][];
            /** Starttime */
            startTime?: string | null;
            /** Terminalstatus */
            terminalStatus?: string | null;
            /**
             * Totaldurationms
             * @default 0
             */
            totalDurationMs: number;
        };
        /** MetricDefinition */
        MetricDefinition: {
            /** Description */
            description: string;
            /** Metricname */
            metricName: string;
            /** Metrictype */
            metricType: string;
            /**
             * Supportspercentiles
             * @default false
             */
            supportsPercentiles: boolean;
            /** Unit */
            unit?: string | null;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "public" | "enterprise" | "internal";
        };
        /** RegressionResponse */
        RegressionResponse: {
            meta: components["schemas"]["ResponseMeta"];
            /** Rows */
            rows: components["schemas"]["RegressionRow"][];
        };
        /** RegressionRow */
        RegressionRow: {
            /** Baselinevalue */
            baselineValue: number;
            /** Currentvalue */
            currentValue: number;
            /** Group */
            group: string;
            /** Relativechange */
            relativeChange: number;
            /**
             * Samplecount
             * @default 0
             */
            sampleCount: number;
            /** Significant */
            significant: boolean;
        };
        /**
         * ResponseMeta
         * @description Server-attached metadata on every response — explainability.
         *
         *     Customers can use these fields to verify what window/data backed a
         *     given response, especially useful for debugging cache vs. live calls.
         */
        ResponseMeta: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "cube" | "bq";
            /**
             * Cachehit
             * @default false
             */
            cacheHit: boolean;
            effectiveRange: components["schemas"]["EffectiveRange"];
            /**
             * Freshnessat
             * Format: date-time
             */
            freshnessAt: string;
            /** Samplecount */
            sampleCount: number;
        };
        /** SessionDetail */
        SessionDetail: {
            /** Appkey */
            appKey?: string | null;
            /** Characterid */
            characterId?: string | null;
            /** Endtime */
            endTime?: string | null;
            /** Events */
            events: components["schemas"]["SessionTimelineEvent"][];
            /** Experienceid */
            experienceId?: string | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Sessionid */
            sessionId: string;
            /** Starttime */
            startTime?: string | null;
        };
        /** SessionListResponse */
        SessionListResponse: {
            meta: components["schemas"]["ResponseMeta"];
            /** Nextcursor */
            nextCursor?: string | null;
            /** Sessions */
            sessions: components["schemas"]["SessionSummary"][];
        };
        /** SessionSummary */
        SessionSummary: {
            /** Appkey */
            appKey?: string | null;
            /** Characterid */
            characterId?: string | null;
            /**
             * Durationsec
             * @default 0
             */
            durationSec: number;
            /** Endtime */
            endTime?: string | null;
            /**
             * Errorcount
             * @default 0
             */
            errorCount: number;
            /** Experienceid */
            experienceId?: string | null;
            /**
             * Interactioncount
             * @default 0
             */
            interactionCount: number;
            /**
             * P95Endtoendms
             * @default 0
             */
            p95EndToEndMs: number;
            /** Sessionid */
            sessionId: string;
            /** Starttime */
            startTime?: string | null;
        };
        /** SessionTimelineEvent */
        SessionTimelineEvent: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            } | null;
            /**
             * Eventtime
             * Format: date-time
             */
            eventTime: string;
            /** Interactionid */
            interactionId?: string | null;
            /** Metricname */
            metricName: string;
            /** Metrictype */
            metricType?: string | null;
            /** Processor */
            processor?: string | null;
            /** Status */
            status?: string | null;
            /** Value */
            value?: number | null;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Errorcount */
            errorCount: number;
            /** Interactions */
            interactions: number;
            meta: components["schemas"]["ResponseMeta"];
            /** P50Endtoendms */
            p50EndToEndMs: number;
            /** P95Endtoendms */
            p95EndToEndMs: number;
            /** P99Endtoendms */
            p99EndToEndMs: number;
            /** Sessions */
            sessions: number;
            /** Uniqueendusers */
            uniqueEndUsers: number;
        };
        /** TimeseriesPoint */
        TimeseriesPoint: {
            /**
             * Bucketstart
             * Format: date-time
             */
            bucketStart: string;
            /** Group */
            group?: string | null;
            /** Value */
            value?: number | null;
        };
        /** TimeseriesResponse */
        TimeseriesResponse: {
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "minute" | "hour" | "day";
            /** Measure */
            measure: string;
            meta: components["schemas"]["ResponseMeta"];
            /** Points */
            points: components["schemas"]["TimeseriesPoint"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    breakdown_v1_analytics_breakdown_get: {
        parameters: {
            query?: {
                measure?: string;
                group_by?: string;
                range?: string;
                limit?: number;
                segment?: string | null;
                metric_name?: string | null;
                metric_name_prefix?: string | null;
                character_id?: string | null;
                app_key?: string | null;
                experience_id?: string | null;
                end_user_id?: string | null;
                provider?: string | null;
                model?: string | null;
                processor?: string | null;
                status?: string | null;
            };
            header?: {
                "CONVAI-API-KEY"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interaction_trace_v1_analytics_interactions__interaction_id__get: {
        parameters: {
            query?: never;
            header?: {
                "CONVAI-API-KEY"?: string | null;
            };
            path: {
                interaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_catalog_v1_analytics_metrics_catalog_get: {
        parameters: {
            query?: never;
            header?: {
                "CONVAI-API-KEY"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cube_query_v1_analytics_query_post: {
        parameters: {
            query?: never;
            header?: {
                "CONVAI-API-KEY"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CubeQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CubeQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regression_detection_v1_analytics_regression_detection_get: {
        parameters: {
            query?: {
                measure?: string;
                baseline_range?: string;
                current_range?: string;
                group_by?: string;
                threshold?: number;
            };
            header?: {
                "CONVAI-API-KEY"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_analytics_sessions_get: {
        parameters: {
            query?: {
                range?: string;
                sort?: string;
                limit?: number;
                cursor?: string | null;
                character_id?: string | null;
                app_key?: string | null;
                experience_id?: string | null;
                end_user_id?: string | null;
            };
            header?: {
                "CONVAI-API-KEY"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_detail_v1_analytics_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                "CONVAI-API-KEY"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_v1_analytics_summary_get: {
        parameters: {
            query?: {
                range?: string;
                character_id?: string | null;
                app_key?: string | null;
                experience_id?: string | null;
            };
            header?: {
                "CONVAI-API-KEY"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeseries_v1_analytics_timeseries_get: {
        parameters: {
            query?: {
                measure?: string;
                granularity?: "minute" | "hour" | "day";
                range?: string;
                group_by?: string | null;
                segment?: string | null;
                metric_name?: string | null;
                metric_name_prefix?: string | null;
                character_id?: string | null;
                app_key?: string | null;
                experience_id?: string | null;
                end_user_id?: string | null;
                provider?: string | null;
                model?: string | null;
                processor?: string | null;
                status?: string | null;
            };
            header?: {
                "CONVAI-API-KEY"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
